version: '3.8'

services:

  nginx-web:
    image: nginx:alpine
    container_name: nginx-proxy-web
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/certs:/etc/nginx/certs:ro
      - ./logs-nginx:/var/log/nginx
    networks:
      - default
      - other-containers

  nginx-gen:
    image: jwilder/docker-gen:latest
    command: -notify-sighup nginx-proxy-web -watch -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-proxy-gen
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - default
      - other-containers
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-proxy-le
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/certs:/etc/nginx/certs:rw
      - ./data/nginx/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
      NGINX_PROXY_CONTAINER: nginx-proxy-web
      DEFAULT_EMAIL: default@default.com
    networks:
      - default
      - other-containers
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    external:
      name: proxy
  other-containers:
    external:
      name: services